# Generated by Django 5.1.4 on 2025-01-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
